# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "http" {
    address        = "https://tf.kaipov.com/myretail"
    lock_address   = "https://tf.kaipov.com/myretail"
    password       = "eKZwgmr2t2imrfvM7TxxscyVxHX7c2HLAy8GGM8x"
    unlock_address = "https://tf.kaipov.com/myretail"
    username       = "ayyhs3fzu6FkHZeQfQErERZNZbVnbVuVCu2nMkrp"
  }
}
